# Sử dụng Python base image
FROM python:3.9-slim

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép file peer vào container
COPY peer.py .
COPY utils.py .
COPY requirements.txt .

# Tạo thư mục để lưu file
RUN mkdir -p /app/files/pieces /app/files/uploads

# Cài đặt các thư viện Python cần thiết
RUN pip install --no-cache-dir -r requirements.txt

# Lệnh chạy peer
CMD ["python", "peer.py"]
